baseURL = 'https://warmsignull.github.io/'
languageCode = 'en-us'
title = 'Warm Signull'
theme = 'minimal'
summaryLength = 30
enableRobotsTXT = true
[module]
  [[module.mounts]]
    source = 'content'
    target = 'content'
    excludeFiles = ['**/*.org']

[params]
description = 'Systems-level language design and tooling, documented as a long-term body of work.'

[[params.social]]
name = 'GitHub'
url = 'https://github.com/warmsignull'

[[params.social]]
name = 'Mastodon'
url = 'https://mastodon.social/@warmsignull'

[[params.social]]
name = 'Bluesky'
url = 'https://bsky.app/profile/warmsignull.bsky.social'

[[params.social]]
name = 'Substack'
url = 'https://warmsignull.substack.com'

[[params.donations]]
name = 'Support Me'
url = '/support/'

[[params.donations]]
name = 'Ko-fi'
url = 'https://ko-fi.com/warmsignull'

[[params.donations]]
name = 'Patreon'
url = 'https://www.patreon.com/warmsignull'

[pagination]
pagerSize = 10

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'
weight = 2

[[menu.main]]
identifier = 'topics'
name = 'Topics'
url = '/topics/'
weight = 3

[[menu.main]]
identifier = 'archive'
name = 'Archive'
url = '/archive/'
weight = 5

[[menu.main]]
identifier = 'support'
name = 'Support Me'
url = '/support/'
weight = 6

[[menu.main]]
identifier = 'contact'
name = 'Contact'
url = '/contact/'
weight = 7
